version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SendMigrationReport"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1p435cjpnrqim"
s3_prefix = "SendMigrationReport"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"

