AWSTemplateFormatVersion: 2010-09-09
Description: >-
  SendMigrationReport

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  sendMigrationReport:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.sendMigrationReport
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: Sends the migration
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          RECEIPIENTS: luismarcilio@gmail.com,luismarcilio@yahoo.com.br
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
