AWSTemplateFormatVersion: 2010-09-09
Description: >-
  SendMigrationReport

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  sendMigrationReport:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.sendMigrationReport
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: Sends the migration
      Environment:
        Variables:
          RECEIPIENTS: Luis marcilio De Oliveira <Luismarcilio.DeOliveira@amdocs.com>; Luigi Menna <Luigi.Menna@amdocs.com>; Andrea Moncaro <Andrea.Moncaro@amdocs.com>; Stefano Diglio <Stefano.Diglio@amdocs.com>; Mirco Tozzi <Mirco.Tozzi@amdocs.com>; Luciano Paltracca <Luciano.Paltracca@amdocs.com>
          HOST: smtp-mail.outlook.com
          USERNAME: deolivel@amdocs.com
          PASSWORD: Iflscience04
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId: !Ref SendMigrationReportApi

  SendMigrationReportApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      TracingEnabled: True
      EndpointConfiguration: REGIONAL

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${SendMigrationReportApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
